name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
   contents: read
   pages: write
   id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true


jobs:
    coverage:
        runs-on: ubuntu-latest
        name: Coverage report
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Test coverage
              uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                  annotations: failed-tests
                  test-script: npm run test:coverage
                  threshold: 80

    deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup Pages
          uses: actions/configure-pages@v2
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v1
          with:
            # Upload entire repository
            path: './coverage'
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v1