name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        name: Coverage report
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Test coverage
              uses: ./ # Uses an action in the root directory
              with:
                  annotations: failed-tests
                  test-script: npm run test:coverage